### ISSUE TITLE
PNG bits/dim is actually a little bit lower if you only count data bytes

### ISSUE THREAD

**Issue by ericjang** [fhkingma/bitswap#1]
Hi, nice work on this paper!

According to the [PNG file format spec](https://github.com/fhkingma/bitswap/blob/master/benchmark_compress.py#L51), PNG images have an 8-byte file header that does not contain image content, followed by 3 "sections" (the header, data, and ending), each of which has a 4-byte section header. If you only count the IDAT bytes, the bits/dim for PNG compression actually comes out to be a little bit lower than reported in the paper:

MNIST:
png: 2.80 bits/dim                   
png (IDAT only): 2.22 bits/dim

Cifar10:
png: 5.87 bits/dim
png (IDAT only): 5.72 bits/dim

Below is the compression function that will reproduce this result. I didn't re-run this on ImageNet.
```
from PIL.PngImagePlugin import getchunks
def pimg_compress_v2(format='PNG', **params):
  def compress_fun(images):
    compressed_data = bytearray()
    for image in images:
      img = pimg.fromarray(image)
      for chunk_type, chunk_data, crc in getchunks(img, optimize=True):
        if chunk_type == b'IDAT':
          compressed_data.extend(chunk_data)
    return compressed_data
  return compress_fun
```

**Comment by fhkingma** [comment]
Hi Eric!

Thanks for opening the issue! Sorry for the late response. I'll try to implement the corrected code as soon as possible.

Friso

**Comment by fhkingma** [comment]
Hi Eric,

I re-ran the experiments with a correction for the header. The results for PNG are indeed a little bit better. I'll submit a new version to arXiv with the corrected results asap.

Friso
