### ISSUE TITLE
Error: device-side assert triggered

### ISSUE THREAD

**Issue by ziqi-zhang** [fhkingma/bitswap#3]
Hi, I ran `python demo_compress.py` on a lena image and got the following error. I found it's in the second iteration of line 142 in demo_compress.py when zi is 1.

![image](https://user-images.githubusercontent.com/17118335/66269322-b9f46800-e879-11e9-89c2-69b9f075a5a0.png)

Besides, I also get some error at line 141 in demo_compress.py in the second iteration when zi is 1.

![image](https://user-images.githubusercontent.com/17118335/66269279-54a07700-e879-11e9-9720-da49b05fe895.png)

It's wired because I only ran the demo code.

**Comment by ziqi-zhang** [comment]
And I found that's because zcentres is of the shape (4,2048,1024), but zsymtop has some number larger than 1023, so an index error occurs.

**Comment by fhkingma** [comment]
Hi Charlie,

I just saw your e-mail. I'll try to remove the bug this weekend. You will
hear from me soon.

Friso Kingma

Op ma 7 okt. 2019 om 06:17 schreef Charlie <notifications@github.com>:

**Comment by fhkingma** [comment]
Hi Charlie,

Could you provide me the image you are compressing?

Friso Kingma

Op do 10 okt. 2019 om 10:26 schreef Friso Kingma <fhkingma@gmail.com>:

**Comment by fhkingma** [comment]
Hi Charlie!

I updated the repo. You should download the imagenetcrop_bins.zip file to
compress with demo_compress.py. Apparently you were using the wrong
discretization bins file.

Please let me know if you have any questions or trouble.

Op do 17 okt. 2019 om 11:06 schreef Friso Kingma <fhkingma@gmail.com>:
