### ISSUE TITLE
No such file or directory: 'data/imagenet/train/train.npy'

### ISSUE THREAD

**Issue by ObsisMc** [fhkingma/bitswap#9]
After I run `mpiexec -np 1 python imagenetcrop_train.py --nz=4 --width=256`
![图片](https://user-images.githubusercontent.com/71996633/189485650-577c4146-18df-4823-9a7d-7cb0727f1601.png)
How can I solve it?

**Comment by developDstore** [comment]
@ObsisMc hi pal, I also met this problem, may I ask you how to solve it?
